APP_NAME=SMS
APP_ENV=local
APP_KEY=base64:drtXR+hs09l/XZMvUrRFUmpqpOYoA5bvcnWlPoWNXc8=
APP_DEBUG=true
APP_URL=http://localhost

LOG_CHANNEL=stack

DB_CONNECTION=mysql
DB_HOST=127.0.0.1
DB_PORT=3306
DB_DATABASE=sms
DB_USERNAME=root
DB_PASSWORD=1234

MS_SQL_SERVERNAME=192.168.4.248
MS_SQL_DBNAME=JACQDATA
MS_SQL_USERNAME=sku
MS_SQL_PASSWORD=sku2020
MS_SQL_PORT=1433

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_CONNECTION=sync
SESSION_DRIVER=file
SESSION_LIFETIME=120

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"

MAIL_DRIVER=smtp
MAIL_HOST=45.127.89.242
MAIL_PORT=26
MAIL_USERNAME=sms@sutlejtextiles.com
MAIL_PASSWORD=sms@123
MAIL_ENCRYPTION=null
MAIL_FROM_NAME=noreply@sms
MAIL_FROM_ADDRESS=sms@sutlejtextiles.com

DO_SPACES_KEY=M4I3LCVPUDXE3Z2ZIRV5
DO_SPACES_SECRET=90i6Ae1OSePVpaeSfJ3cBCmw6t7ylNSdnqJsaIGe2vU
DO_SPACES_ENDPOINT=https://sgp1.digitaloceanspaces.com 
DO_SPACES_REGION=sgp1
DO_SPACES_BUCKET=sms-storage

JS_CSS_VERSION=1

SUTLEJ_WHITELIST_IP_CHECK=0

REMOTE_IMPORT_CRON_FLAG=1
